from app.schemas.appointment import (
    AppointmentCreate,
    AppointmentRead,
    AppointmentUpdate,
    ScheduleBlockCreate,
    ScheduleBlockRead,
)
from app.schemas.billing import (
    ExpenseCreate,
    ExpenseRead,
    InvoiceCreate,
    InvoiceItemCreate,
    InvoiceItemRead,
    InvoiceRead,
    InvoiceUpdate,
)
from app.schemas.clinic import (
    ClinicBranchCreate,
    ClinicBranchRead,
    ClinicBranchUpdate,
    ClinicCreate,
    ClinicRead,
    ClinicSubscriptionChange,
    ClinicSubscriptionEventRead,
    ClinicSummaryRead,
    ClinicUpdate,
)
from app.schemas.consultation import (
    CheckoutProductItem,
    CheckoutResult,
    CheckoutServiceItem,
    ConsultationCheckoutRequest,
    ConsultationCreate,
    ConsultationItemCreate,
    ConsultationItemRead,
    ConsultationRead,
    ConsultationUpdate,
)
from app.schemas.crm import (
    OwnerPreferencesRead,
    OwnerPreferencesUpdate,
    PhotoEvolutionItem,
    SurveyCreate,
    SurveyRead,
)
from app.schemas.events import AuditLogRead, NotificationRead
from app.schemas.inventory import (
    InventoryLotCreate,
    InventoryLotRead,
    InventoryProductCreate,
    InventoryProductRead,
    InventoryProductUpdate,
    StockEntryCreate,
)
from app.schemas.pet import (
    ClinicalAlertCreate,
    ClinicalAlertRead,
    ClinicalAlertUpdate,
    OwnerLinkRead,
    OwnerTransferRequest,
    OwnerTransferResponse,
    PetCreate,
    PetRead,
    PetUpdate,
    PetWeightCreate,
    PetWeightRead,
)
from app.schemas.product import ProductCreate, ProductRead, ProductUpdate
from app.schemas.purchase import (
    PurchaseOrderCreate,
    PurchaseOrderItemCreate,
    PurchaseOrderItemRead,
    PurchaseOrderRead,
    PurchaseOrderUpdate,
)
from app.schemas.reminder import PendingReminder, ReminderRunResult, ReminderSchedule, ReminderStage
from app.schemas.sale import SaleCreate, SaleProductItem, SaleResult
from app.schemas.services import ServiceCreate, ServiceRead, ServiceUpdate
from app.schemas.staff import ProfileUpdate, UserCreate, UserRead, UserUpdate
from app.schemas.vaccination import (
    DoseRead,
    PetVaccinationPlanRead,
    PlanStepCreate,
    PlanStepRead,
    VaccinationAssignRequest,
    VaccinationPlanCreate,
    VaccinationPlanRead,
    VaccinationPlanUpdate,
)
from app.schemas.waitlist import WaitlistCreate, WaitlistRead, WaitlistUpdate

__all__ = [
    "AppointmentCreate",
    "AppointmentRead",
    "AppointmentUpdate",
    "AuditLogRead",
    "ClinicBranchCreate",
    "ClinicBranchRead",
    "ClinicBranchUpdate",
    "ClinicCreate",
    "ClinicRead",
    "ClinicSubscriptionChange",
    "ClinicSubscriptionEventRead",
    "ClinicSummaryRead",
    "ClinicUpdate",
    "ClinicalAlertCreate",
    "ClinicalAlertRead",
    "ClinicalAlertUpdate",
    "CheckoutProductItem",
    "CheckoutResult",
    "CheckoutServiceItem",
    "ConsultationCheckoutRequest",
    "ConsultationCreate",
    "ConsultationItemCreate",
    "ConsultationItemRead",
    "ConsultationRead",
    "ConsultationUpdate",
    "DoseRead",
    "ExpenseCreate",
    "ExpenseRead",
    "InventoryProductCreate",
    "InventoryProductRead",
    "InventoryProductUpdate",
    "InventoryLotCreate",
    "InventoryLotRead",
    "InvoiceCreate",
    "InvoiceItemCreate",
    "InvoiceItemRead",
    "InvoiceRead",
    "InvoiceUpdate",
    "OwnerLinkRead",
    "OwnerContactUpdate",
    "OwnerPreferencesRead",
    "OwnerPreferencesUpdate",
    "OwnerTransferRequest",
    "OwnerTransferResponse",
    "NotificationRead",
    "PendingReminder",
    "PetCreate",
    "PetRead",
    "PetUpdate",
    "PetVaccinationPlanRead",
    "PetWeightCreate",
    "PetWeightRead",
    "PhotoEvolutionItem",
    "PlanStepCreate",
    "PlanStepRead",
    "ProductCreate",
    "ProductRead",
    "ProductUpdate",
    "ProfileUpdate",
    "PurchaseOrderCreate",
    "PurchaseOrderItemCreate",
    "PurchaseOrderItemRead",
    "PurchaseOrderRead",
    "PurchaseOrderUpdate",
    "ReminderRunResult",
    "ReminderSchedule",
    "ReminderStage",
    "SaleCreate",
    "SaleProductItem",
    "SaleResult",
    "ScheduleBlockCreate",
    "ScheduleBlockRead",
    "ServiceCreate",
    "ServiceRead",
    "ServiceUpdate",
    "StockEntryCreate",
    "SurveyCreate",
    "SurveyRead",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "VaccinationAssignRequest",
    "VaccinationPlanCreate",
    "VaccinationPlanRead",
    "VaccinationPlanUpdate",
    "WaitlistCreate",
    "WaitlistRead",
    "WaitlistUpdate",
]
